from fastapi import APIRouter, UploadFile, File
from fastapi.responses import FileResponse
from backend.agents.graph import audit_graph
from backend.agents.state import AuditState
from backend.rag.policy_store import embed_policy
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import mm
import shutil, os, uuid, datetime

router = APIRouter()

UPLOAD_DIR = os.getenv("UPLOAD_DIR", "./data/uploads")

@router.get("/")
def root():
    return {"status": "Healthcare Audit API is running"}

@router.post("/upload-and-analyze")
async def analyze(files: list[UploadFile] = File(...)):
    run_id = str(uuid.uuid4())
    run_dir = os.path.join(UPLOAD_DIR, run_id)
    os.makedirs(run_dir, exist_ok=True)

    saved_paths = []
    doc_type_map = {}

    for file in files:
        path = os.path.join(run_dir, file.filename)
        with open(path, "wb") as f:
            shutil.copyfileobj(file.file, f)
        saved_paths.append(path)
        doc_type_map[file.filename] = file.filename

        if "policy" in file.filename.lower():
            content = open(path, "rb").read().decode("utf-8", errors="ignore")
            embed_policy(content)

    initial_state: AuditState = {
        "uploaded_files": saved_paths,
        "doc_type_map": doc_type_map,
        "parsed_docs": {},
        "hospital_bill_data": None,
        "insurance_policy_text": None,
        "discharge_summary_text": None,
        "prescription_text": None,
        "lab_report_text": None,
        "pharmacy_bill_data": None,
        "billing_result": None,
        "insurance_result": None,
        "claim_guide": None,
        "dispute_letter": None,
        "errors": []
    }

    result = audit_graph.invoke(initial_state)

    return {
        "run_id": run_id,
        "billing_result": result.get("billing_result"),
        "insurance_result": result.get("insurance_result"),
        "claim_guide": result.get("claim_guide"),
        "dispute_letter": result.get("dispute_letter"),
        "errors": result.get("errors")
    }


@router.post("/generate-report")
async def generate_report(data: dict):
    run_id = data.get("run_id", "report")
    billing = data.get("billing_result") or {}
    insurance = data.get("insurance_result") or {}
    claim_guide = data.get("claim_guide", "")
    dispute_letter = data.get("dispute_letter", "")

    os.makedirs("data/reports", exist_ok=True)
    output_path = f"data/reports/{run_id}_audit_report.pdf"

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('CustomTitle',
        parent=styles['Title'],
        fontSize=22,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=4)

    heading_style = ParagraphStyle('CustomHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#4f46e5'),
        spaceBefore=14,
        spaceAfter=6)

    normal_style = ParagraphStyle('CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#333333'),
        spaceAfter=4,
        leading=16)

    small_style = ParagraphStyle('Small',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        leading=14)

    bold_style = ParagraphStyle('Bold',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#111111'),
        fontName='Helvetica-Bold')

    red_style = ParagraphStyle('Red',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#dc2626'))

    green_style = ParagraphStyle('Green',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#16a34a'))

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=20*mm,
        bottomMargin=20*mm
    )
    story = []

    # ── HEADER ──────────────────────────────────────────
    story.append(Paragraph("Healthcare Bill Audit Report", title_style))
    story.append(Paragraph(
        f"Generated on: {datetime.datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        small_style))
    story.append(Paragraph(
        "This report was generated by the AI Healthcare Bill and Insurance Audit Assistant. "
        "It analyses your hospital bill for overcharges, checks insurance coverage, and provides "
        "a step-by-step claim filing guide.",
        small_style))
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor('#e5e7eb'),
        spaceAfter=12))

    # ── SECTION 1: BILL SUMMARY ──────────────────────────
    story.append(Paragraph("1. Bill Summary", heading_style))

    total_billed = billing.get('total_billed', 0)
    fair_amount = billing.get('estimated_fair_amount', 0)
    savings = billing.get('total_potential_savings', 0)
    flags = billing.get('flags', [])
    flagged = [f for f in flags if f.get('flag_type') != 'ok']

    summary_data = [
        ['Description', 'Amount'],
        ['Total Bill Amount', f"Rs {total_billed:,.0f}"],
        ['Estimated Fair Amount', f"Rs {fair_amount:,.0f}"],
        ['Potential Overcharges Detected', f"Rs {savings:,.0f}"],
        ['Total Line Items in Bill', str(len(flags))],
        ['Flagged Items Requiring Attention', str(len(flagged))],
    ]
    summary_table = Table(summary_data, colWidths=[100*mm, 70*mm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4f46e5')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1), (-1,-1),
            [colors.HexColor('#f9fafb'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e5e7eb')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('FONTNAME', (0,3), (0,3), 'Helvetica-Bold'),
        ('TEXTCOLOR', (1,3), (1,3), colors.HexColor('#dc2626')),
        ('FONTNAME', (1,3), (1,3), 'Helvetica-Bold'),
        ('TEXTCOLOR', (1,5), (1,5), colors.HexColor('#dc2626')),
        ('FONTNAME', (1,5), (1,5), 'Helvetica-Bold'),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    if billing.get('summary_for_patient'):
        story.append(Paragraph("What this means for you:", bold_style))
        story.append(Paragraph(billing['summary_for_patient'], normal_style))

    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#e5e7eb'),
        spaceAfter=8))

    # ── SECTION 2: DETAILED BILL BREAKDOWN ──────────────
    story.append(Paragraph("2. Detailed Bill Breakdown", heading_style))
    story.append(Paragraph(
        "Every charge in your hospital bill is listed below. "
        "Highlighted rows have been flagged by our audit engine.",
        small_style))
    story.append(Spacer(1, 6))

    flag_colors_map = {
        'duplicate':    colors.HexColor('#fef9c3'),
        'inflated':     colors.HexColor('#fee2e2'),
        'unauthorised': colors.HexColor('#ede9fe'),
        'negotiable':   colors.HexColor('#dcfce7'),
        'unbundled':    colors.HexColor('#ffedd5'),
        'ok':           colors.HexColor('#f9fafb'),
    }

    bill_data = [['#', 'Item Description', 'Billed (Rs)', 'Status', 'Excess (Rs)']]
    for i, f in enumerate(flags, 1):
        bill_data.append([
            str(i),
            f.get('line_item', '')[:38],
            f"{f.get('billed_amount', 0):,.0f}",
            f.get('flag_type', 'ok').upper(),
            f"{f.get('excess_amount', 0):,.0f}" if f.get('excess_amount', 0) > 0 else '-'
        ])

    bill_table = Table(
        bill_data,
        colWidths=[10*mm, 78*mm, 26*mm, 26*mm, 26*mm])
    ts = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#e5e7eb')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('ALIGN', (2,0), (-1,-1), 'RIGHT'),
        ('ALIGN', (0,0), (0,-1), 'CENTER'),
    ])
    for i, f in enumerate(flags, 1):
        ft = f.get('flag_type', 'ok')
        bg = flag_colors_map.get(ft, colors.white)
        ts.add('BACKGROUND', (0,i), (-1,i), bg)
        if ft != 'ok':
            ts.add('FONTNAME', (3,i), (3,i), 'Helvetica-Bold')
            ts.add('TEXTCOLOR', (3,i), (3,i), colors.HexColor('#dc2626'))
    bill_table.setStyle(ts)
    story.append(bill_table)
    story.append(Spacer(1, 10))

    # Flag colour legend
    legend_data = [['Colour Legend:',
        'DUPLICATE = charged twice',
        'INFLATED = overpriced',
        'UNAUTHORISED = not ordered',
        'NEGOTIABLE = can be waived']]
    legend_table = Table(legend_data, colWidths=[28*mm, 36*mm, 30*mm, 38*mm, 38*mm])
    legend_table.setStyle(TableStyle([
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#666666')),
        ('BACKGROUND', (1,0), (1,0), colors.HexColor('#fef9c3')),
        ('BACKGROUND', (2,0), (2,0), colors.HexColor('#fee2e2')),
        ('BACKGROUND', (3,0), (3,0), colors.HexColor('#ede9fe')),
        ('BACKGROUND', (4,0), (4,0), colors.HexColor('#dcfce7')),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(legend_table)
    story.append(Spacer(1, 10))

    # Detailed flag explanations
    if flagged:
        story.append(Paragraph("Explanation of Each Flagged Charge:", bold_style))
        story.append(Spacer(1, 4))
        for i, f in enumerate(flagged, 1):
            story.append(Paragraph(
                f"{i}. {f.get('line_item', '')} — {f.get('flag_type','').upper()}",
                bold_style))
            story.append(Paragraph(
                f"Finding: {f.get('plain_explanation', '')}",
                normal_style))
            story.append(Paragraph(
                f"Action: {f.get('action', '')}",
                green_style))
            story.append(Spacer(1, 6))

    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#e5e7eb'),
        spaceAfter=8))

    # ── SECTION 3: INSURANCE COVERAGE ───────────────────
    story.append(Paragraph("3. Insurance Coverage Analysis", heading_style))
    coverage = insurance.get('coverage_results', [])
    if coverage:
        story.append(Paragraph(
            "Each flagged charge was checked against your uploaded insurance policy document:",
            small_style))
        story.append(Spacer(1, 6))
        for i, c in enumerate(coverage, 1):
            story.append(Paragraph(f"{i}. {c.get('item', '')}", bold_style))
            story.append(Paragraph(str(c.get('coverage', '')), normal_style))
            story.append(Spacer(1, 6))
    else:
        story.append(Paragraph(
            "No insurance policy was uploaded. Upload your policy document "
            "to get a coverage analysis for each charge.",
            normal_style))

    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#e5e7eb'),
        spaceAfter=8))

    # ── SECTION 4: MISSING DOCUMENTS ────────────────────
    missing = insurance.get('missing_documents', [])
    if missing:
        story.append(Paragraph("4. Missing Documents for Insurance Claim", heading_style))
        story.append(Paragraph(
            "You must collect these documents before filing your insurance claim:",
            small_style))
        story.append(Spacer(1, 6))
        for m in missing:
            story.append(Paragraph(f"☐   {m}", red_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor('#e5e7eb'),
            spaceAfter=8))

    # ── SECTION 5: CLAIM GUIDE ───────────────────────────
    if claim_guide:
        story.append(Paragraph("5. Step-by-Step Claim Filing Guide", heading_style))
        story.append(Paragraph(
            "Follow these steps carefully to file your insurance claim "
            "and dispute any overcharged items:",
            small_style))
        story.append(Spacer(1, 6))
        for line in claim_guide.split('\n'):
            if line.strip():
                story.append(Paragraph(line.strip(), normal_style))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor('#e5e7eb'),
            spaceAfter=8))

    # ── SECTION 6: DISPUTE LETTER ────────────────────────
    if dispute_letter:
        story.append(Paragraph("6. Formal Dispute Letter", heading_style))
        story.append(Paragraph(
            "You can use this letter to formally dispute overcharged items "
            "with the hospital billing department:",
            small_style))
        story.append(Spacer(1, 6))
        for line in dispute_letter.split('\n'):
            if line.strip():
                story.append(Paragraph(line.strip(), normal_style))
        story.append(Spacer(1, 10))

    # ── FOOTER ──────────────────────────────────────────
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor('#e5e7eb'),
        spaceAfter=8))
    story.append(Paragraph(
        "DISCLAIMER: This report is generated by an AI system and is for "
        "informational purposes only. Please consult a certified medical billing "
        "expert or legal advisor before taking any action based on this report.",
        small_style))

    doc.build(story)

    return FileResponse(
        output_path,
        media_type="application/pdf",
        filename="healthcare_audit_report.pdf"
    )